server:
  port: 8081

spring:
  application:
    name: customer-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/customer-platform

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
