server:
  port: 8082

spring:
  application:
    name: loyalty-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/customer_platform}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/customer-platform

services:
  notification:
    base-url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
