services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: customer_platform
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    container_name: keycloak
    command:
      - start-dev
      - --spi-email-template-provider=freemarker
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/providers/email-otp-authenticator-dev-kc-26.5.4.jar:/opt/keycloak/providers/email-otp-authenticator-dev-kc-26.5.4.jar
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"