server:
  port: 8083

spring:
  application:
    name: notification-service

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
